### ISSUE TITLE
Title Format and add custom tag using vscode settings

### ISSUE THREAD

**Issue by nurjamil** [guyanyijiu/go-struct-tag#5]
Can we add title format, with space separation ? and can we add our own struct tag using vscode settings?

love the extension btw, thank you for the work

**Comment by guyanyijiu** [comment]
> Can we add title format, with space separation ?

I don't quite understand, can you give me some examples?

**Comment by guyanyijiu** [comment]
I've released [1.0.3](https://github.com/guyanyijiu/go-struct-tag/releases/tag/v0.3.0) to support custom tags.
